//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVDatabase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TVTable
    {
        public TVTable()
        {
            CurrentlyRunning = true;
            Views = 0;
            Likes = 0;
            Dislikes = 0;
        }
        public int ID { get; set; }

        [Display(Name = "Show Name")]
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string ShowName { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        [Required]
        [StringLength(30)]
        public string Genre { get; set; }

        [Display(Name = "Started On")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateFrom { get; set; }

        [Display(Name = "Ended On")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DateTo { get; set; }


        [Display(Name = "Number of Seasons")]
        public Nullable<int> NumberOfSeasons { get; set; }

        [Display(Name = "Currently Running")]
        public bool CurrentlyRunning { get; set; }

        public string Description { get; set; }

        [Display(Name = "Starring")]
        public string Actors { get; set; }

        [Display(Name = "Highest Domestic Viewing Figures")]
        public string PeakViewers { get; set; }

        [Display(Name = "Broadcasting Network")]
        public string Network { get; set; }

        public string Image { get; set; }

        [Range(0, 10)]
        [Display(Name = "IMDB Rating")]
        public Nullable<double> Rating { get; set; }

        [Display(Name = "Produced In")]
        public string Country { get; set; }

        [Display(Name = "TV Base Views")]
        public int Views { get; set; }

        [Display(Name = "TV Base Likes")]
        public int Likes { get; set; }

        [Display(Name = "TV Base Dislikes")]
        public int Dislikes { get; set; }

        [Display(Name = "Deletion Password")]
        public string SecretPassword { get; set; }
    }
}
