//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVDatabase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TVTable
    {
        public int ID { get; set; }

        [Display(Name = "Show Name")]
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string ShowName { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        [Required]
        [StringLength(30)]
        public string Genre { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> NumberOfSeasons { get; set; }
        public Nullable<bool> CurrentlyRunning { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Actors { get; set; }
        [Required]
        public string PeakViewers { get; set; }
        [Required]
        public string Network { get; set; }
        [Required]
        public string Image { get; set; }
        [Range(0, 10)]
        public Nullable<double> Rating { get; set; }
        [Required]
        public string Country { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<int> Dislikes { get; set; }
        public string SecretPassword { get; set; }
    }
}
